# Generated by Django 5.2.8 on 2025-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Development Steps')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Not Started', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, editable=False, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DevelopmentTracker',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('project_type', models.CharField(blank=True, choices=[('GM', 'Ground-Mount'), ('RT', 'Rooftop'), ('OT', 'Other')], max_length=16, null=True)),
                ('project_details', models.CharField(blank=True, choices=[('GM_FIXED', 'gm-fixed'), ('GM_TRACK', 'gm-tracking'), ('BALLASTED', 'ballasted'), ('ROOFTOP', 'rooftop')], max_length=32, null=True)),
                ('offtake_structure', models.CharField(blank=True, choices=[('FTM_UTIL', 'FTM-Utility'), ('FTM_DIST', 'FTM-Distributed'), ('BTM', 'BTM')], max_length=16, null=True)),
                ('size_ac_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('size_dc_mw', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('county', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
    ]
