# Generated by Django 5.2.8 on 2025-11-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_project_options_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentstep',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
