# Generated by Django 5.2.8 on 2025-11-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_alter_developmentstep_options_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='developmentstep',
            table='"app"."DevTracker"',
        ),
        migrations.AlterModelTable(
            name='project',
            table='steps_project',
        ),
    ]
