# Generated by Django 5.2.8 on 2025-12-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_alter_developmentstep_table_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
