# Generated by Django 5.2.8 on 2025-12-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_alter_project_city_alter_project_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('responsibility', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=64)),
                ('phone2', models.CharField(blank=True, max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='steps.project')),
            ],
            options={
                'db_table': 'steps_project_contact',
            },
        ),
    ]
