# Generated by Django 5.2.8 on 2025-12-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_add_devstep_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
    ]
