# Generated by Django 5.2.8 on 2025-12-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_projectcontact_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lease_option_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lease_option_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
