# Generated by Django 5.2.8 on 2025-12-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0015_permitrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteconomics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectincentives',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='steporder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
