# Generated by Django 5.2.8 on 2025-12-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_company(apps, schema_editor):
    Company = apps.get_model("steps", "Company")
    Project = apps.get_model("steps", "Project")

    default_company, _ = Company.objects.get_or_create(
        name="Default Company",
        defaults={
            "domain": "",
            "contact_email": "",
            "is_active": True,
        },
    )

    # Assign any existing projects without a company to the default
    Project.objects.filter(company__isnull=True).update(company=default_company)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("steps", "0016_alter_projecteconomics_id_alter_projectincentives_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("contact_email", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_companies", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "steps_company",
            },
        ),
        migrations.CreateModel(
            name="CompanyMembership",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("member", "Member"), ("viewer", "Viewer")], default="member", max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("invited", "Invited")], default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="steps.company")),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invited_company_memberships", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="company_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "steps_company_membership",
                "unique_together": {("user", "company")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="company",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="steps.company"),
        ),
        migrations.RunPython(create_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="projects", to="steps.company"),
        ),
    ]

