--
-- PostgreSQL database dump
--

\restrict hFhl0WgJ9egA9I6gQgWwRtB22pqUUIZXEhbFnwu25s4JgKXFB59bxJFNIJyArZ6

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP INDEX IF EXISTS app.steps_project_project_name_f4c28730_like;
DROP INDEX IF EXISTS app.steps_project_legal_name_1c63c7d0_like;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_project_name_key;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_pkey;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_legal_name_key;
DROP TABLE IF EXISTS app.steps_project;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: steps_project; Type: TABLE; Schema: app; Owner: postgres
--

CREATE TABLE app.steps_project (
    id integer NOT NULL,
    project_name character varying(255) NOT NULL,
    legal_name character varying(255) NOT NULL,
    project_type character varying(16),
    project_details character varying(16),
    offtake_structure character varying(16),
    size_ac_mw numeric(10,3),
    size_dc_mw numeric(10,3),
    latitude numeric(10,6),
    longitude numeric(10,6),
    state character varying(2),
    county character varying(255),
    city character varying(255),
    address character varying(255),
    other character varying(255)
);


ALTER TABLE app.steps_project OWNER TO postgres;

--
-- Name: steps_project_id_seq; Type: SEQUENCE; Schema: app; Owner: postgres
--

ALTER TABLE app.steps_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.steps_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: steps_project; Type: TABLE DATA; Schema: app; Owner: postgres
--

COPY app.steps_project (id, project_name, legal_name, project_type, project_details, offtake_structure, size_ac_mw, size_dc_mw, latitude, longitude, state, county, city, address, other) FROM stdin;
1	New Project	New Legal Entity	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
9	New Project 1763951279473	New Legal Entity 1763951279473	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
10	New Project 1763951288439	New Legal Entity 1763951288439	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- Name: steps_project_id_seq; Type: SEQUENCE SET; Schema: app; Owner: postgres
--

SELECT pg_catalog.setval('app.steps_project_id_seq', 10, true);


--
-- Name: steps_project steps_project_legal_name_key; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_legal_name_key UNIQUE (legal_name);


--
-- Name: steps_project steps_project_pkey; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_pkey PRIMARY KEY (id);


--
-- Name: steps_project steps_project_project_name_key; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_project_name_key UNIQUE (project_name);


--
-- Name: steps_project_legal_name_1c63c7d0_like; Type: INDEX; Schema: app; Owner: postgres
--

CREATE INDEX steps_project_legal_name_1c63c7d0_like ON app.steps_project USING btree (legal_name varchar_pattern_ops);


--
-- Name: steps_project_project_name_f4c28730_like; Type: INDEX; Schema: app; Owner: postgres
--

CREATE INDEX steps_project_project_name_f4c28730_like ON app.steps_project USING btree (project_name varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict hFhl0WgJ9egA9I6gQgWwRtB22pqUUIZXEhbFnwu25s4JgKXFB59bxJFNIJyArZ6

