--
-- PostgreSQL database dump
--

\restrict hFhl0WgJ9egA9I6gQgWwRtB22pqUUIZXEhbFnwu25s4JgKXFB59bxJFNIJyArZ6

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP INDEX IF EXISTS app.steps_project_project_name_f4c28730_like;
DROP INDEX IF EXISTS app.steps_project_legal_name_1c63c7d0_like;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_project_name_key;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_pkey;
ALTER TABLE IF EXISTS ONLY app.steps_project DROP CONSTRAINT IF EXISTS steps_project_legal_name_key;
DROP TABLE IF EXISTS app.steps_project;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: steps_project; Type: TABLE; Schema: app; Owner: postgres
--

CREATE TABLE app.steps_project (
    id integer NOT NULL,
    project_name character varying(255) NOT NULL,
    legal_name character varying(255) NOT NULL,
    project_type character varying(16),
    project_details character varying(16),
    offtake_structure character varying(16),
    size_ac_mw numeric(10,3),
    size_dc_mw numeric(10,3),
    latitude numeric(10,6),
    longitude numeric(10,6),
    state character varying(2),
    county character varying(255),
    city character varying(255),
    address character varying(255),
    other character varying(255)
);


ALTER TABLE app.steps_project OWNER TO postgres;

--
-- Name: steps_project_id_seq; Type: SEQUENCE; Schema: app; Owner: postgres
--

ALTER TABLE app.steps_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.steps_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: steps_project; Type: TABLE DATA; Schema: app; Owner: postgres
--

COPY app.steps_project (id, project_name, legal_name, project_type, project_details, offtake_structure, size_ac_mw, size_dc_mw, latitude, longitude, state, county, city, address, other) FROM stdin;
1	New Project	New Legal Entity	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
9	New Project 1763951279473	New Legal Entity 1763951279473	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
10	New Project 1763951288439	New Legal Entity 1763951288439	RT	GM_FIXED	FTM_UTIL	5.000	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- Name: steps_project_id_seq; Type: SEQUENCE SET; Schema: app; Owner: postgres
--

SELECT pg_catalog.setval('app.steps_project_id_seq', 10, true);


--
-- Name: steps_project steps_project_legal_name_key; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_legal_name_key UNIQUE (legal_name);


--
-- Name: steps_project steps_project_pkey; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_pkey PRIMARY KEY (id);


--
-- Name: steps_project steps_project_project_name_key; Type: CONSTRAINT; Schema: app; Owner: postgres
--

ALTER TABLE ONLY app.steps_project
    ADD CONSTRAINT steps_project_project_name_key UNIQUE (project_name);


--
-- Name: steps_project_legal_name_1c63c7d0_like; Type: INDEX; Schema: app; Owner: postgres
--

CREATE INDEX steps_project_legal_name_1c63c7d0_like ON app.steps_project USING btree (legal_name varchar_pattern_ops);


--
-- Name: steps_project_project_name_f4c28730_like; Type: INDEX; Schema: app; Owner: postgres
--

CREATE INDEX steps_project_project_name_f4c28730_like ON app.steps_project USING btree (project_name varchar_pattern_ops);


--
-- DevTracker table for development steps
--

CREATE TABLE IF NOT EXISTS "app"."DevTracker" (
    id SERIAL PRIMARY KEY,
    "Development Steps" TEXT,
    phase INTEGER,
    start_date DATE,
    end_date DATE,
    duration_days INTEGER,
    status VARCHAR(100),
    dev_type VARCHAR(32),
    planned_spend NUMERIC(12, 2),
    actual_spend NUMERIC(12, 2),
    project_id INTEGER REFERENCES app.steps_project(id) ON DELETE CASCADE
);


--
-- Seed template development steps (project_id IS NULL for templates)
--

INSERT INTO "app"."DevTracker" 
("Development Steps", phase, dev_type, project_id) 
VALUES
('Site Assessment', 1, 'development', NULL),
('Environmental Review', 2, 'development', NULL),
('Permitting & Licensing', 3, 'permitting', NULL),
('Engineering Design', 4, 'development', NULL),
('Equipment Procurement', 5, 'procurement', NULL),
('Construction', 6, 'construction', NULL),
('Grid Interconnection', 7, 'interconnection', NULL),
('Final Inspection', 8, 'development', NULL),
('Commissioning', 9, 'operations', NULL),
('Commercial Operation', 10, 'operations', NULL);


--
-- Seed development steps for existing projects (1, 9, 10)
--

INSERT INTO "app"."DevTracker" 
("Development Steps", phase, dev_type, status, start_date, end_date, planned_spend, project_id) 
VALUES
('Site Assessment', 1, 'development', 'In Progress', '2025-01-15', '2025-02-15', 50000.00, 1),
('Environmental Review', 2, 'development', 'Completed', '2025-02-01', '2025-03-15', 75000.00, 1),
('Permitting & Licensing', 3, 'permitting', 'In Progress', '2025-03-01', '2025-05-30', 120000.00, 1),
('Engineering Design', 4, 'development', 'Planned', '2025-04-01', '2025-06-30', 250000.00, 1),
('Equipment Procurement', 5, 'procurement', 'Planned', '2025-05-15', '2025-08-15', 1500000.00, 1),
('Construction', 6, 'construction', 'Planned', '2025-07-01', '2025-12-31', 2000000.00, 1),
('Grid Interconnection', 7, 'interconnection', 'Planned', '2025-11-01', '2026-01-31', 300000.00, 1),
('Final Inspection', 8, 'development', 'Planned', '2025-12-15', '2026-02-28', 100000.00, 1),
('Commissioning', 9, 'operations', 'Planned', '2026-01-15', '2026-02-15', 200000.00, 1),
('Commercial Operation', 10, 'operations', 'Planned', '2026-03-01', NULL, 0.00, 1),
('Site Assessment', 1, 'development', 'Completed', '2024-06-01', '2024-07-15', 45000.00, 9),
('Environmental Review', 2, 'development', 'Completed', '2024-07-15', '2024-09-01', 80000.00, 9),
('Permitting & Licensing', 3, 'permitting', 'In Progress', '2024-08-01', '2025-02-28', 150000.00, 9),
('Engineering Design', 4, 'development', 'In Progress', '2024-10-01', '2025-01-31', 280000.00, 9),
('Equipment Procurement', 5, 'procurement', 'Planned', '2025-01-01', '2025-04-30', 1800000.00, 9),
('Construction', 6, 'construction', 'Planned', '2025-03-01', '2025-10-31', 2200000.00, 9),
('Grid Interconnection', 7, 'interconnection', 'Planned', '2025-09-01', '2025-11-30', 350000.00, 9),
('Final Inspection', 8, 'development', 'Planned', '2025-10-15', '2025-12-31', 120000.00, 9),
('Commissioning', 9, 'operations', 'Planned', '2025-11-15', '2025-12-15', 250000.00, 9),
('Commercial Operation', 10, 'operations', 'Planned', '2026-01-01', NULL, 0.00, 9),
('Site Assessment', 1, 'development', 'Completed', '2025-02-01', '2025-03-15', 55000.00, 10),
('Environmental Review', 2, 'development', 'In Progress', '2025-03-15', '2025-05-01', 85000.00, 10),
('Permitting & Licensing', 3, 'permitting', 'Planned', '2025-04-01', '2025-08-31', 135000.00, 10),
('Engineering Design', 4, 'development', 'Planned', '2025-05-01', '2025-07-31', 265000.00, 10),
('Equipment Procurement', 5, 'procurement', 'Planned', '2025-06-15', '2025-09-30', 1650000.00, 10),
('Construction', 6, 'construction', 'Planned', '2025-08-01', '2026-02-28', 2100000.00, 10),
('Grid Interconnection', 7, 'interconnection', 'Planned', '2026-01-01', '2026-03-31', 320000.00, 10),
('Final Inspection', 8, 'development', 'Planned', '2026-02-15', '2026-04-30', 110000.00, 10),
('Commissioning', 9, 'operations', 'Planned', '2026-03-01', '2026-04-01', 220000.00, 10),
('Commercial Operation', 10, 'operations', 'Planned', '2026-04-15', NULL, 0.00, 10);


--
-- PostgreSQL database dump complete
--

\unrestrict hFhl0WgJ9egA9I6gQgWwRtB22pqUUIZXEhbFnwu25s4JgKXFB59bxJFNIJyArZ6

