from django.db import models

class DevelopmentStep(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.TextField(db_column='"Development Steps"')
    sequence = models.IntegerField(null=True, blank=True)
    phase = models.TextField(null=True, blank=True, db_column="phase")
    status = models.CharField(max_length=255, null=True, blank=True, db_column="status")
    start_date = models.DateField(null=True, blank=True, db_column="start_date")
    end_date   = models.DateField(null=True, blank=True, db_column="end_date")

    # generated by the DB — do NOT edit
    duration_days = models.IntegerField(null=True, blank=True, db_column="duration_days", editable=False)

    class Meta:
        db_table = '"public"."DevelopmentTracker"'
        managed = False
